### PR TITLE
some styling

### PR DESCRIPTION
**Pull request by punker76**
playing with the messages view...
- [x] first changes
- [x] invert messages stream as a work around (Xamarin.Forms ListView doesn't allow scroll to bottom)
- [x] show message send time
- [x] prevent selection highlight
- [x] rooms sorting
- [x] rooms styling
- [x] change to theme completely to a white theme http://stackoverflow.com/questions/24102225/changing-the-default-dark-android-theme-to-white-in-xamarin-forms

### CODE REVIEW

**Comment by flagbug** [comment]
Nice!

Maybe we should change to theme completely to a white theme? http://stackoverflow.com/questions/24102225/changing-the-default-dark-android-theme-to-white-in-xamarin-forms

**Comment by punker76** [comment]
@flagbug i'll do this in this pr... :-D

**Comment by punker76** [comment]
@flagbug firstly done with this pr

**Comment by flagbug** [comment]
Thanks @punker76!

**Pull request merged**
